import { Mission } from './mission.model';

export interface Subject {
  id?: string ;               // optional, generated by backend
  name: string;
  description: string;
  missions: Mission[]; 
  showMissions: boolean;  // flag to show/hide missions
}
